import type { BriefStyle } from "./types"

export function getBriefPrompt(category: string, style: BriefStyle): string {
  if (style === "wacky") {
    return getWackyPrompt(category)
  }
  return getRealisticPrompt(category)
}

function getWackyPrompt(category: string): string {
  return [
    `Generate a creative advertising brief for a ridiculous fictional product in the "${category}" category.`,
    "",
    "Make it SPECIFIC and ABSURD. The product should have:",
    "- A distinctive quirk, flaw, or overly-specific use case",
    "- An unexpected combination of features or a bizarre selling point",
    "- A business problem that's hilariously mismatched with the solution",
    "- Enough weird detail to spark creative riffing",
    "",
    "Respond with valid JSON matching this TypeScript interface:",
    "{",
    '  "productName": string,',
    '  "productCategory": string,',
    '  "mainPoint": string,',
    '  "audience": string,',
    '  "businessProblem": string,',
    '  "objective": string,',
    '  "strategy": string,',
    '  "productFeatures": string',
    "}",
    "",
    `The productCategory field MUST be exactly: "${category}"`,
    "",
    "Field requirements:",
    "- mainPoint: A short, absurd phrase (4-8 words) describing the singular weird communication objective",
    "- audience: 1-2 bullet points about the hilariously specific target demographic (use \\n between bullets)",
    "- businessProblem: 1-3 bullet points about the ridiculous business challenge (use \\n between bullets)",
    "- objective: The key absurd outcome the campaign should achieve",
    "- strategy: How this bizarre creative campaign should achieve the objective",
    "- productFeatures: Exactly 3 bullet points describing key absurd features (use \\n between bullets)",
    "",
    "Examples of the absurdity level to aim for:",
    "- A luxury sleeping bag for business meetings",
    "- Edible post-it notes that taste like the priority level",
    "- A meditation app that only works while you're screaming",
    "",
    "Make it weird, specific, and memorable. Do not wrap the JSON in markdown fences or add extra text.",
  ].join("\n")
}

function getRealisticPrompt(category: string): string {
  return [
    `Generate a creative advertising brief for a realistic fictional product in the "${category}" category.`,
    "",
    "Make it SPECIFIC and DIFFERENTIATED. The product should have:",
    "- A concrete market gap or underserved customer need (not just 'better' or 'innovative')",
    "- A distinctive positioning angle or unique value proposition",
    "- Specific product features with measurable benefits or outcomes",
    "- A well-defined target audience with specific demographics, behaviors, and pain points",
    "- Clear business objectives tied to metrics (awareness, consideration, conversion, retention)",
    "- Enough concrete detail to inspire distinctive creative campaigns",
    "",
    "VARY these elements to create diverse briefs:",
    "- Price positioning (luxury, premium, mid-market, budget, value)",
    "- Business model (subscription, one-time purchase, freemium, B2B, D2C)",
    "- Innovation type (category disruption, incremental improvement, category creation)",
    "- Primary customer pain point (time, money, convenience, status, safety, sustainability)",
    "- Distribution channel (retail, direct-to-consumer, B2B, marketplace)",
    "",
    "Respond with valid JSON matching this TypeScript interface:",
    "{",
    '  "productName": string,',
    '  "productCategory": string,',
    '  "mainPoint": string,',
    '  "audience": string,',
    '  "businessProblem": string,',
    '  "objective": string,',
    '  "strategy": string,',
    '  "productFeatures": string',
    "}",
    "",
    `The productCategory field MUST be exactly: "${category}"`,
    "",
    "Field requirements:",
    "- mainPoint: A short, punchy phrase (4-8 words) describing the singular key communication objective",
    "- audience: 1-2 bullet points about who the target demographic is, including specific demographics, psychographics, and behaviors (use \\n between bullets)",
    "- businessProblem: 1-3 bullet points about the specific market challenge this campaign should solve for the business (use \\n between bullets)",
    "- objective: The key measurable outcome the campaign should achieve",
    "- strategy: How this creative campaign should achieve the objective (1-2 sentences)",
    "- productFeatures: Exactly 3 bullet points describing key features with concrete benefits (use \\n between bullets)",
    "",
    "Examples of the specificity level to aim for:",
    "- FlexDesk Pro: A modular standing desk system with built-in cable management and wireless charging, targeting remote workers in small apartments (under 600 sq ft) who struggle with dedicated workspace and need furniture that adapts throughout the day",
    "- SnackLab: A personalized snack subscription using AI taste profiling, targeting health-conscious Gen Z consumers (18-24) with dietary restrictions who want discovery without the guilt of traditional snack boxes",
    "- CareCircle: A family coordination app with medication reminders and appointment scheduling, targeting adult children (35-50) managing care for aging parents across different cities",
    "",
    "Make it believable, strategically grounded, and specific enough to inspire creative advertising concepts.",
    "Avoid generic products - each brief should feel distinct and memorable.",
    "Do not wrap the JSON in markdown fences or add extra text.",
  ].join("\n")
}
